-- MySQL Script generated by MySQL Workbench
-- Tue Feb 19 23:49:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ambiental_monitoring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ambiental_monitoring
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `ambiental_monitoring`;
CREATE SCHEMA IF NOT EXISTS `ambiental_monitoring` DEFAULT CHARACTER SET utf8 ;
USE `ambiental_monitoring` ;

-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipologia` SET('Distretto', 'Edificio', 'Area') NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUtente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Distretto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Distretto` (
  `idDistretto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `alert` SMALLINT(2) NULL,
  PRIMARY KEY (`idDistretto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Edificio` (
  `idEdificio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `idDistretto` INT NOT NULL,
  `alert` SMALLINT(2) NULL,
  PRIMARY KEY (`idEdificio`),
  INDEX `fk_Edificio_Distretto1_idx` (`idDistretto` ASC),
  CONSTRAINT `fk_Edificio_Distretto1`
    FOREIGN KEY (`idDistretto`)
    REFERENCES `ambiental_monitoring`.`Distretto` (`idDistretto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `alert` SMALLINT(2) NOT NULL DEFAULT 0,
  `idEdificio` INT NOT NULL,
  PRIMARY KEY (`idArea`),
  INDEX `fk_Area_Edificio1_idx` (`idEdificio` ASC),
  CONSTRAINT `fk_Area_Edificio1`
    FOREIGN KEY (`idEdificio`)
    REFERENCES `ambiental_monitoring`.`Edificio` (`idEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Sensore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Sensore` (
  `idSensore` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `massimale` FLOAT NOT NULL,
  `frequenzaInvio` INT NOT NULL,
  `ultimoInvio` DATETIME NULL,
  `area` INT NOT NULL,
  `gestore` INT NOT NULL,
  PRIMARY KEY (`idSensore`),
  INDEX `fk_Sensore_Zona1_idx` (`area` ASC),
  INDEX `fk_Sensore_Utente1_idx` (`gestore` ASC),
  CONSTRAINT `fk_Sensore_Zona1`
    FOREIGN KEY (`area`)
    REFERENCES `ambiental_monitoring`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sensore_Utente1`
    FOREIGN KEY (`gestore`)
    REFERENCES `ambiental_monitoring`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ambiental_monitoring`.`Segnale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiental_monitoring`.`Segnale` (
  `idSegnale` INT ZEROFILL NOT NULL,
  `sensore` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `variabileAmbientale` FLOAT NOT NULL,
  `alert` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idSegnale`),
  INDEX `fk_Segnale_Sensore_idx` (`sensore` ASC),
  CONSTRAINT `fk_Segnale_Sensore`
    FOREIGN KEY (`sensore`)
    REFERENCES `ambiental_monitoring`.`Sensore` (`idSensore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
